name: Backend CI

on:
  workflow_dispatch:
  push:
    paths:
      - "tracker/arcadia_tracker/**"
      - ".github/workflows/tracker.yml"
  pull_request:
    branches:
      - main
    paths:
      - "tracker/arcadia_tracker/**"
      - ".github/workflows/tracker.yml"

env:
  CARGO_TERM_COLOR: always

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    container: rust:1.89-bullseye

    services:
      arcadiadb:
        image: postgres
        env:
          POSTGRES_USER: arcadia
          POSTGRES_PASSWORD: password
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    defaults:
      run:
        working-directory: ./tracker/arcadia_tracker

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: ./tracker/arcadia_tracker

      - name: Setup env
        run: |
          set -a
          . ./.env.ci
          set +a
          env | grep -v '^_' >> $GITHUB_ENV

      - name: Setup env
        run: cp -f ./.env.ci .env

      - name: Build
        run: cargo build

      - name: Run tests
        run: cargo test

  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          cache-workspaces: ./

      - name: Check clippy for new warnings
        run: cargo clippy
        env:
          SQLX_OFFLINE: "true"

  formatting:
    name: cargo fmt
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tracker/arcadia_tracker
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
          toolchain: 1.86
          cache-workspaces: ./tracker/arcadia_tracker
      - name: Rustfmt Check
        run: cargo fmt --all -- --check
